### ISSUE TITLE
Por que testes unitários?

### ISSUE THREAD

**Issue by VSVeras** [larien/aprenda-go-com-testes#98]
**No exemplo da página [https://larien.gitbook.io/aprenda-go-com-testes/meta/motivacao](url) está assim**
`var cumprimentos = map[string]string {
  br: "Olá",
  fr: "Bonjour",
  // etc..
}`

**Acredito que deveria ser:**
`var cumprimentos = map[string]string{
	"br": "Olá",
	"fr": "Bonjour",
	// etc..
}`

**Comment by larien** [comment]
Obrigada! Já mandei uma correçãozinha :)
